notifications:
  email:
    on_success: never
    on_failure: change

dist: trusty

os:
  - osx

branches:
  only:
    - master
    - /^__release-.*/

language: node_js
node_js:
  - "7"

cache:
  timeout: 600
  directories:
    - node_modules
    - $HOME/.electron
    - .eslintcache

install:
  - npm install -g yarn@1.3.2
  - yarn install --force

script:
  - yarn lint
  - yarn build:prod
  - yarn test:setup
  - yarn test

after_success:
  - npm run publish

after_failure:
  - yarn test:review
